### ISSUE TITLE
Duda acerca de la creación de los directorios de usuario

### ISSUE THREAD

**Issue by alu0101105741** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct08-filesystem-notes-app-alu0101105741#2]
Buenas, a la hora de crear los diferentes directorios de usuario para guardar sus notas no tengo muy claro si se quiere crear dichos directorios en la raíz del proyecto, en el directorio dist o tendremos que crear un directorio común en el que guardaremos los directorios de los usuarios con las notas. Gracias de antemano.

@esegredo @lgforte

**Comment by esegredo** [comment]
Hola Eric,

El directorio no tiene porqué estar dentro del proyecto, pero si quieres hacerlo así, puedes crearte un directorio aparte del que cuelguen los directorios de los usuarios.

Saludos.

@alu0101105741
